name: Weekly issue metrics
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    steps:
    - name: Get dates for last week
      shell: bash
      run: |

        ##########################################################
        Create report for the previous week
        ##########################################################
        # Get the current date
        current_date=$(date +'%Y-%m-%d')

        # Calculate the previous week
        previous_date=$(date -d "$current_date -1 week" +'%Y-%m-%d')
        
        echo "$previous_date..$current_date"
        echo "prev_week=$previous_date..$current_date" >> "$GITHUB_ENV"
        
        ##########################################################
        Create report for the previous month
        ##########################################################
        
        # Calculate the first day of the previous month
        #first_day=$(date -d "last month" +%Y-%m-01)

        # Calculate the last day of the previous month
        #last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

        #Set an environment variable with the date range
        #echo "$first_day..$last_day"
        #echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool for opened issues last week
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:mikaelacaron/Basic-Car-Maintenance is:issue created:${{ env.prev_week }}'

    - name: Create issue for opened issues
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: ${{ env.prev_week }} opened issues
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: mikaelacaron
        labels: |
          weekly-report

    - name: Run issue-metrics tool for closed issues last week
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:mikaelacaron/Basic-Car-Maintenance is:issue closed:${{ env.prev_week }}'

    - name: Create issue for closed issues
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: ${{ env.prev_week }} closed issues
        content-filepath: ./issue_metrics.md
        assignees: mikaelacaron
        labels: |
          weekly-report

    - name: Run issue-metrics tool for prs opened last week
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:mikaelacaron/Basic-Car-Maintenance is:pr created:${{ env.prev_week }}'

    - name: Create issue for opened prs
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: ${{ env.prev_week }} opened prs
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: mikaelacaron
        labels: |
          weekly-report

    - name: Run issue-metrics tool for prs closed last week
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:mikaelacaron/Basic-Car-Maintenance is:pr closed:${{ env.prev_week }}'

    - name: Create issue for closed prs last week
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: ${{ env.prev_week }} closed prs
        content-filepath: ./issue_metrics.md
        assignees: mikaelacaron
        labels: |
          weekly-report
